manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/xmorph42
  projects:
    - name: zmk
      remote: urob-zmk
      revision: xmorph42_ergo_s1
      import: app/west.yml
  self:
    path: config
